sqlite_wrapper: db::table Class Reference
db::table Class Reference
a base wrapper class for a database table
Public Member Functions
table (const db::string &table_name)
table
virtual void set (db::base &b, vec_type &v)
Detailed Description
a base wrapper class for a database table
Constructor & Destructor Documentation
db::table::table (const db::string & table_name) [inline]
table
qualifier : _table_name(table_name)
access public
Returns:
Parameters:
table_name as const db::string &
Author:
T. Schröder (explodus@gmx.de)
Date:
30.4.2010 22:34
References DB_TEXT.
Member Function Documentation
void db::table::set (db::base & b, vec_type & v) [inline, virtual]
todo: do somethin with this exception, rethrow or anything
References db::base::begin(), db::base::commit(), db::base::execute_ptr(), and db::base::rollback().
Generated for sqlite_wrapper