sqlite_wrapper: db::base Class Reference
db::base Class Reference
datenbank interface
Public Member Functions
void begin ()
begins SQL transaction
void commit ()
commits SQL transaction
void connect (const std::string &file)
open the specified db
query & execute (const string &cmd)
execute SQL statement
query_ptr execute_ptr (const string &cmd)
execute SQL statement
void rollback ()
cancels active SQL transaction
Protected Member Functions
void throw_error (int status)
got called from db::query if a sqlite error was occured
Detailed Description
datenbank interface
Member Function Documentation
void db::base::begin () [inline]
begins SQL transaction
qualifier
access public
Returns:
void
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:49
References throw_error().
Referenced by db::table::set().
void db::base::commit () [inline]
commits SQL transaction
qualifier
access public
Returns:
void
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:50
References throw_error().
Referenced by db::table::set().
void db::base::connect (const std::string & file) [inline]
open the specified db
qualifier
access public
Returns:
void
Parameters:
file as const std::string &
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:49
References throw_error().
db::query & db::base::execute (const string & cmd) [inline]
execute SQL statement
qualifier
access public
Returns:
query&
Parameters:
cmd as const string &
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:50
db::query_ptr db::base::execute_ptr (const string & cmd) [inline]
execute SQL statement
qualifier
access public
Returns:
db::query_ptr
Parameters:
cmd as const string &
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:51
Referenced by db::table::set().
void db::base::rollback () [inline]
cancels active SQL transaction
qualifier
access public
Returns:
void
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:50
References throw_error().
Referenced by db::table::set().
void db::base::throw_error (int status) [inline, protected]
got called from db::query if a sqlite error was occured
qualifier
access protected
Returns:
void
Parameters:
status as int
Author:
T. Schroeder (explodus@gmx.de)
Date:
15.4.2010 13:49
References DB_TEXT.
Referenced by begin(), commit(), connect(), db::query::execute(), and rollback().
Generated for sqlite_wrapper