sqlite_wrapper: db::row Class Reference
db::row Class Reference
table rows interface
Public Member Functions
row (const row &r)
row
row (query *query_, unsigned row_)
row
row ()
~row ()
~row
iterator begin ()
begin iterator
const_iterator begin () const
const begin iterator
bool empty () const
returns true if the container is empty
iterator end ()
end iterator
const_iterator end () const
const end iterator
void fill (sqlite3_stmt *stm)
fill
bool operator== (const row &t) const
operator==
param * operator[] (const string &field_title)
operator[]
reference operator[] (size_type field_num)
get a value by number
const_reference operator[] (size_type field_num) const
get a value by number
void push_back (const value_type &v)
push a param to the container
reverse_iterator rbegin ()
begin reverse iterator
reverse_iterator rend ()
end reverse iterator
size_type size () const
container size
param & value (size_type field_num)
get a value by number
const param & value (size_type field_num) const
get a value by number
Detailed Description
table rows interface
Constructor & Destructor Documentation
db::row::row () [inline]
Todo:
correct this...
db::row::row (db::query * query_, unsigned row_) [inline]
row
qualifier : _query(query_), _row(row_)
access public
Returns:
Parameters:
query_ as query *
row_ as unsigned
Date:
20:2:2009 9:24
db::row::row (const row & r) [inline]
row
qualifier : _query(r._query), _row(r._row)
access public
Returns:
Parameters:
r as const row &
Date:
20:2:2009 9:23
References begin(), end(), and size().
db::row::~row () [inline]
~row
qualifier
access public
Returns:
Date:
20:2:2009 9:23
Member Function Documentation
db::row::iterator db::row::begin () [inline]
begin iterator
qualifier
access public
Returns:
db::row::iterator
Date:
20:2:2009 9:21
db::row::const_iterator db::row::begin () const [inline]
const begin iterator
qualifier const
access public
Returns:
db::row::const_iterator
Date:
20:2:2009 9:21
Referenced by operator[](), row(), and value().
bool db::row::empty () const [inline]
returns true if the container is empty
qualifier const
access public
Returns:
bool
Date:
20:2:2009 9:19
db::row::iterator db::row::end () [inline]
end iterator
qualifier
access public
Returns:
db::row::iterator
Date:
20:2:2009 9:20
db::row::const_iterator db::row::end () const [inline]
const end iterator
qualifier const
access public
Returns:
db::row::const_iterator
Date:
20:2:2009 9:21
Referenced by row().
void db::row::fill (sqlite3_stmt * stm) [inline]
fill
qualifier
access public
Returns:
void
Parameters:
stm as sqlite3_stmt *
Date:
20:2:2009 9:18
bool db::row::operator== (const row & t) const [inline]
operator==
qualifier const
access public
Returns:
bool
Parameters:
t as const row &
Date:
20:2:2009 9:19
db::param * db::row::operator[] (const string & field_title) [inline]
operator[]
Todo:
need an implementation
qualifier
access public
Returns:
param*
Parameters:
field_title as const string &
Date:
20:2:2009 9:21
db::row::reference db::row::operator[] (size_type field_num) [inline]
get a value by number
qualifier
access public
Returns:
db::row::reference
Parameters:
field_num as size_type
Date:
20:2:2009 9:21
References begin().
db::row::const_reference db::row::operator[] (size_type field_num) const [inline]
get a value by number
qualifier const
access public
Returns:
db::row::const_reference
Parameters:
field_num as size_type
Date:
20:2:2009 9:22
References begin().
void db::row::push_back (const value_type & v) [inline]
push a param to the container
qualifier
access public
Returns:
void
Parameters:
v as const value_type &
Date:
20:2:2009 9:18
db::row::reverse_iterator db::row::rbegin () [inline]
begin reverse iterator
qualifier
access public
Returns:
db::row::reverse_iterator
Date:
20:2:2009 9:20
db::row::reverse_iterator db::row::rend () [inline]
end reverse iterator
qualifier
access public
Returns:
db::row::reverse_iterator
Date:
20:2:2009 9:20
db::row::size_type db::row::size () const [inline]
container size
qualifier const
access public
Returns:
db::row::size_type
Date:
20:2:2009 9:20
Referenced by row().
db::param & db::row::value (size_type field_num) [inline]
get a value by number
qualifier
access public
Returns:
param&
Parameters:
field_num as size_type
Date:
20:2:2009 9:23
References begin().
const db::param & db::row::value (size_type field_num) const [inline]
get a value by number
qualifier const
access public
Returns:
const param&
Parameters:
field_num as size_type
Date:
20:2:2009 9:23
References begin().
Generated for sqlite_wrapper