sqlite_wrapper: db::upd Class Reference
db::upd Class Reference
helper class for generating update sql expressions
Public Member Functions
upd (const string &t, const string &d1, const string &d2)
upd
upd (const string &t, const string &d)
upd (const string &t)
operator string () const
string overload
upd & operator% (const db::field &f)
insert a new field with it name and the value
upd & operator% (const expr::base &e)
insert a sql where expression through the operator % overload
template<typename T >
upd & set (const field &f, const T &val)
insert a new field with it name and the value
upd & set (const field &f, const string &val)
insert a new field with it name and the value
string str () const
same as the string operator overload, more stl like
upd & where (const expr::base &e)
qualifier
access public
Detailed Description
helper class for generating update sql expressions
Member Function Documentation
db::upd & db::upd::operator% (const db::field & f) [inline]
insert a new field with it name and the value
qualifier
access public
Returns:
upd &
Parameters:
f as const db::field &
Date:
15.4.2010 13:58
References db::field::values().
db::upd & db::upd::operator% (const expr::base & e) [inline]
insert a sql where expression through the operator % overload
qualifier
access public
Returns:
upd &
Parameters:
e as const expr::base &
Date:
15.4.2010 13:55
References where().
template<typename T > upd& db::upd::set (const field & f, const T & val) [inline]
insert a new field with it name and the value
qualifier
access public
Returns:
upd&
Parameters:
f as const field &
val as const T &
Date:
15.4.2010 13:58
db::upd & db::upd::set (const field & f, const string & val) [inline]
insert a new field with it name and the value
qualifier
access public
Returns:
upd&
Parameters:
f as const field &
val as const string &
Date:
15.4.2010 13:56
db::string db::upd::str () const [inline]
same as the string operator overload, more stl like
qualifier const
access public
Returns:
db::string
Date:
15.4.2010 13:59
References DB_TEXT, and db::split::join().
db::upd & db::upd::where (const expr::base & e) [inline]
qualifier
access public
Returns:
upd&
Parameters:
e as const expr::base &
Date:
15.4.2010 13:55
Referenced by operator%().
Generated for sqlite_wrapper