sqlite_wrapper: db::sel Class Reference
db::sel Class Reference
helper class, generates SELECT SQL statements
Public Member Functions
sel (const sel &s)
copy constructor
sel (const string &tablename, const string &delim1, const string &delim2)
constructor
sel (const string &tablename, const string &delim)
constructor
sel (const string &tablename)
constructor
sel ()
constructor
virtual ~sel ()
destructor
virtual sel & clear ()
clear
virtual sel & distinct (bool d)
distinct
virtual sel & group_by (string gb)
group_by
virtual sel & having (string h)
having
virtual sel & having (const expr::base &h)
having
virtual sel & join (const field_pair &f)
join
virtual sel & limit (int value)
limit
virtual sel & offset (int value)
offset
virtual operator string () const
db::string overload
virtual sel & operator% (const expr::base &e)
adds a where expression
virtual sel & operator, (const string &s)
adds a column name
virtual sel & operator< (const field_pair &f)
joins two fields
sel & operator= (const sel &s)
simple copy operator
virtual sel & order_by (string ob, bool ascending=true)
order_by
virtual sel & result (string r, string alias=DB_TEXT(""))
result
virtual sel & result_max (string r, string alias=DB_TEXT(""))
result_max
virtual sel & result_no_delim (string r, string alias=DB_TEXT(""))
result_no_delim
virtual sel & source (string s, string alias=DB_TEXT(""))
source
virtual string str () const
same as the string operator overload, more stl like
virtual sel & where (string w)
where
virtual sel & where (const expr::base &w)
where
Detailed Description
helper class, generates SELECT SQL statements
Constructor & Destructor Documentation
db::sel::~sel () [inline, virtual]
destructor
qualifier
access public
Returns:
Date:
20.4.2010 10:41
Member Function Documentation
db::sel & db::sel::clear () [inline, virtual]
clear
qualifier
access virtual public
Returns:
sel &
Date:
20:2:2009 14:01
db::sel & db::sel::distinct (bool d) [inline, virtual]
distinct
qualifier
access virtual public
Returns:
sel &
Parameters:
d as bool
Date:
20:2:2009 14:02
db::sel & db::sel::group_by (string gb) [inline, virtual]
group_by
qualifier
access virtual public
Returns:
sel &
Parameters:
gb as string
Date:
20:2:2009 14:01
db::sel & db::sel::having (string h) [inline, virtual]
having
qualifier
access virtual public
Returns:
sel &
Parameters:
h as string
Date:
20:2:2009 14:01
db::sel & db::sel::having (const expr::base & h) [inline, virtual]
having
qualifier
access virtual public
Returns:
sel &
Parameters:
h as const expr::base &
Date:
20:2:2009 14:01
References db::expr::base::str().
db::sel & db::sel::join (const field_pair & f) [inline, virtual]
join
qualifier
access virtual public
Returns:
sel &
Parameters:
f as const field_pair&
Date:
20:2:2009 14:02
Referenced by operator<().
db::sel & db::sel::limit (int value) [inline, virtual]
limit
qualifier
access virtual public
Returns:
sel &
Parameters:
value as int
Date:
20:2:2009 14:02
db::sel & db::sel::offset (int value) [inline, virtual]
offset
qualifier
access virtual public
Returns:
sel &
Parameters:
value as int
Date:
20:2:2009 14:02
db::sel & db::sel::order_by (string ob, bool ascending = true) [inline, virtual]
order_by
qualifier
access virtual public
Returns:
sel &
Parameters:
ob as string
ascending as bool
Date:
20:2:2009 14:00
References DB_TEXT.
db::sel & db::sel::result (string r, string alias = DB_TEXT("")) [inline, virtual]
result
qualifier
access virtual public
Returns:
sel &
Parameters:
r as string
alias as string
Date:
20:2:2009 14:02
References DB_TEXT.
db::sel & db::sel::result_max (string r, string alias = DB_TEXT("")) [inline, virtual]
result_max
qualifier
access virtual public
Returns:
sel &
Parameters:
r as string
alias as string
Date:
20:2:2009 14:02
References DB_TEXT.
db::sel & db::sel::result_no_delim (string r, string alias = DB_TEXT("")) [inline, virtual]
result_no_delim
qualifier
access virtual public
Returns:
sel &
Parameters:
r as string
alias as string
Date:
20:2:2009 14:02
References DB_TEXT.
db::sel & db::sel::source (string s, string alias = DB_TEXT("")) [inline, virtual]
source
qualifier
access virtual public
Returns:
sel &
Parameters:
s as string
alias as string
Date:
20:2:2009 14:01
References DB_TEXT.
Referenced by sel().
db::string db::sel::str () const [inline, virtual]
same as the string operator overload, more stl like
qualifier const
access public
Returns:
db::string
Date:
15.4.2010 13:59
db::sel & db::sel::where (string w) [inline, virtual]
where
qualifier
access virtual public
Returns:
sel &
Parameters:
w as string
Date:
20:2:2009 14:01
db::sel & db::sel::where (const expr::base & w) [inline, virtual]
where
qualifier
access virtual public
Returns:
sel &
Parameters:
w as const expr::base &
Date:
20:2:2009 14:01
Referenced by operator%().
Generated for sqlite_wrapper