sqlite_wrapper: db::ins Class Reference
db::ins Class Reference
helper class, generates INSERT SQL statements
Public Member Functions
ins (const string &tab, const string &delim1, const string &delim2)
ins (const string &tab, const string &delim)
ins (const string &tab)
~ins ()
destructor
ins & clear_values ()
clear_values
operator string () const
operator string
ins & operator% (const db::field &f)
operator%
string str () const
str
template<typename T >
ins & values (const string &t, const T &v)
values
ins & values (string t, string v, param_types p=e_int)
values
ins & values (string t, param *v)
values
Detailed Description
helper class, generates INSERT SQL statements
Constructor & Destructor Documentation
db::ins::~ins () [inline]
destructor
qualifier
access public
Returns:
Date:
20.4.2010 20:39
Member Function Documentation
db::ins & db::ins::clear_values () [inline]
clear_values
qualifier
access public
Returns:
ins &
Date:
20:2:2009 9:07
db::ins::operator string () const
operator string
qualifier const
access public
Returns:
Date:
20:2:2009 11:04
db::ins & db::ins::operator% (const db::field & f) [inline]
operator%
qualifier
access public
Returns:
ins &
Parameters:
f as const db::field &
Date:
20:2:2009 9:07
References values(), and db::field::values().
db::string db::ins::str () const [inline]
str
qualifier const
access public
Returns:
db::string
Date:
20:2:2009 11:05
References DB_TEXT, db::split_map::join_fields(), and db::split_map::join_values().
template<typename T > ins& db::ins::values (const string & t, const T & v) [inline]
values
qualifier
access public
Returns:
ins &
Parameters:
t as const string &
v as const T &
Date:
20:2:2009 11:07
References values().
Referenced by values().
db::ins & db::ins::values (string t, string v, param_types p = e_int) [inline]
values
qualifier
access public
Returns:
ins &
Parameters:
t as string
v as string
p as param_types
Date:
20:2:2009 9:07
References DB_TEXT.
db::ins & db::ins::values (string t, param * v) [inline]
values
qualifier
access public
Returns:
ins &
Parameters:
t as string
v as param *
Date:
20:2:2009 9:07
References DB_TEXT, db::param::get_type(), and db::param::str().
Referenced by operator%().
Generated for sqlite_wrapper