sqlite_wrapper: db::query Class Reference
db::query Class Reference
cursor interface
Public Member Functions
query (const query &q)
query
query (base &base_)
query
query ()
query
~query ()
~query
iterator begin ()
begin iterator
const_iterator begin () const
begin iterator
bool empty () const
is container empty?
iterator end ()
end iterator
const_iterator end () const
end iterator
void execute (const string &cmd)
execute
bool f_empty () const
is container empty?
fiterator fbegin ()
begin iterator
const_fiterator fbegin () const
begin iterator
fiterator fend ()
end iterator
const_fiterator fend () const
end iterator
const field * getFieldInfo (unsigned iField) const
getFieldInfo
int getIdOf (const string &sField) const
get id from field title
row & getRow (size_type row_num)
get a row by number
const row & getRow (size_type row_num) const
get a row by number
string getTitleOf (unsigned iField) const
get id from field title
bool operator== (const query &t) const
operator==
reference operator[] (size_type row_num)
get a row by number
const_reference operator[] (size_type row_num) const
get a row by number
void push_back (const fvalue_type &v)
push a field title to the field container
void push_back (const value_type &v)
push a row to the row container
size_type size () const
container size
Detailed Description
cursor interface
Constructor & Destructor Documentation
db::query::query () [inline]
query
Returns:
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:54
db::query::query (base & base_) [inline]
query
qualifier
access public
Returns:
Parameters:
base_ as base &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
db::query::query (const query & q) [inline]
query
qualifier
access public
Returns:
Parameters:
q as const query &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
References begin(), end(), fbegin(), and fend().
db::query::~query () [inline]
~query
qualifier
access public
Returns:
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
Member Function Documentation
db::query::iterator db::query::begin () [inline]
begin iterator
qualifier
access public
Returns:
db::query::iterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:58
db::query::const_iterator db::query::begin () const [inline]
begin iterator
qualifier const
access public
Returns:
db::query::const_iterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
Referenced by getRow(), operator[](), and query().
bool db::query::empty () const [inline]
is container empty?
qualifier const
access public
Returns:
bool
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::query::iterator db::query::end () [inline]
end iterator
qualifier
access public
Returns:
db::query::iterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:58
db::query::const_iterator db::query::end () const [inline]
end iterator
qualifier const
access public
Returns:
db::query::const_iterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
Referenced by query().
void db::query::execute (const string & cmd) [inline]
execute
qualifier
access public
Returns:
void
Parameters:
cmd as const string &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
Todo:
portabel machen
References db::base::throw_error().
bool db::query::f_empty () const [inline]
is container empty?
qualifier const
access public
Returns:
bool
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::query::fiterator db::query::fbegin () [inline]
begin iterator
qualifier
access public
Returns:
db::query::fiterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::query::const_fiterator db::query::fbegin () const [inline]
begin iterator
qualifier const
access public
Returns:
db::query::const_fiterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
Referenced by query().
db::query::fiterator db::query::fend () [inline]
end iterator
qualifier
access public
Returns:
db::query::fiterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::query::const_fiterator db::query::fend () const [inline]
end iterator
qualifier const
access public
Returns:
db::query::const_fiterator
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
Referenced by query().
const db::field * db::query::getFieldInfo (unsigned iField) const [inline]
getFieldInfo
qualifier const
access public
Returns:
const field*
Parameters:
iField as unsigned
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
int db::query::getIdOf (const string & sField) const [inline]
get id from field title
qualifier const
access public
Returns:
int
Parameters:
sField as const string &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::row & db::query::getRow (size_type row_num) [inline]
get a row by number
qualifier
access public
Returns:
row&
Parameters:
row_num as size_type
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
References begin().
const db::row & db::query::getRow (size_type row_num) const [inline]
get a row by number
qualifier const
access public
Returns:
const row&
Parameters:
row_num as size_type
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:55
References begin().
db::string db::query::getTitleOf (unsigned iField) const [inline]
get id from field title
qualifier const
access public
Returns:
db::string
Parameters:
iField as unsigned
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
References DB_TEXT.
bool db::query::operator== (const query & t) const [inline]
operator==
qualifier const
access public
Returns:
bool
Parameters:
t as const query &
Author:
Torsten Schroeder
schroeder@ipe-chemnitz.de / explodus@gmx.de
Date:
31.3.2010 22:01
db::query::reference db::query::operator[] (size_type row_num) [inline]
get a row by number
qualifier
access public
Returns:
db::query::reference
Parameters:
row_num as size_type
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
References begin().
db::query::const_reference db::query::operator[] (size_type row_num) const [inline]
get a row by number
qualifier const
access public
Returns:
db::query::const_reference
Parameters:
row_num as size_type
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
References begin().
void db::query::push_back (const fvalue_type & v) [inline]
push a field title to the field container
qualifier
access public
Returns:
void
Parameters:
v as const fvalue_type &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
void db::query::push_back (const value_type & v) [inline]
push a row to the row container
qualifier
access public
Returns:
void
Parameters:
v as const value_type &
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
db::query::size_type db::query::size () const [inline]
container size
qualifier const
access public
Returns:
db::query::size_type
Author:
T. Schroeder (explodus@gmx.de)
Date:
31.3.2010 21:57
Generated for sqlite_wrapper