sqlite_wrapper: summary of all operator overloads
summary of all operator overloads
Functions
db::upd::operator string () const
string overload
virtual db::del::operator string () const
db::string overload
virtual db::sel::operator string () const
db::string overload
virtual sel & db::sel::operator% (const expr::base &e)
adds a where expression
virtual sel & db::sel::operator, (const string &s)
adds a column name
virtual sel & db::sel::operator< (const field_pair &f)
joins two fields
sel & db::sel::operator= (const sel &s)
simple copy operator
Function Documentation
db::upd::operator string () const [inherited]
string overload
qualifier const
access public
Returns:
db::string
Date:
15.4.2010 13:59
virtual db::del::operator string () const [virtual, inherited]
db::string overload
qualifier const
access virtual public
Returns:
db::string
Date:
20.4.2010 10:09
Reimplemented from db::sel.
virtual db::sel::operator string () const [virtual, inherited]
db::string overload
qualifier const
access virtual public
Returns:
Date:
20.4.2010 10:57
Reimplemented in db::del.
db::sel & db::sel::operator% (const expr::base & e) [inline, virtual, inherited]
adds a where expression
qualifier
access public
Returns:
sel & - itself
Parameters:
e as const expr::base & - where expression
Date:
20.4.2010 10:53
References db::expr::base::str(), and db::sel::where().
virtual sel& db::sel::operator, (const string & s) [virtual, inherited]
adds a column name
qualifier
access public
Returns:
sel & - itself
Parameters:
s as const string & - column name
Date:
20.4.2010 10:51
db::sel & db::sel::operator< (const field_pair & f) [inline, virtual, inherited]
joins two fields
qualifier
access virtual public
Returns:
sel & - itself
Parameters:
f as const field_pair &
Date:
20.4.2010 10:56
References db::sel::join().
db::sel & db::sel::operator= (const sel & s) [inline, inherited]
simple copy operator
qualifier
access public
Returns:
sel & - itself
Parameters:
s as const sel &
Date:
20.4.2010 10:54
Generated for sqlite_wrapper